### ISSUE TITLE
plz init for new projects

### ISSUE THREAD

**Issue by jimsimon** [PlzPkg/plz#1]
Given that I am a user
And that I'm starting a new project
And that I don't have an existing plz.yaml file
When I issue the plz init command
Then I am asked for a project name
And a version number
Then a new plz.yaml file is created with the following contents:

name: provided name here
description: provided description here

**Comment by mcchicken** [comment]
Beautiful.

**Comment by jimsimon** [comment]
I should probably clarify the format of the name and version.  I'll clean it up tomorrow.

**Comment by joineral32** [comment]
Added commits to satisfy 'And that I don't have an existing plz.yaml file'
